import type { Metadata } from "next";
import NavComponent from "@/components/NavComponent";
import { Koulen, Marvel } from "next/font/google";
import "./globals.css";

const koulen = Koulen({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-koulen",
});

const marvel = Marvel({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-marvel",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${koulen.variable} ${marvel.variable}`}>
      <body>
        <NavComponent />
        {children}
      </body>
    </html>
  );
}
